### ISSUE TITLE
TS2729 [ERROR]: Property 'buffer' is used before its initialization.

### ISSUE THREAD

**Issue by ThatBlockyPenguin** [jsimpson/binary_reader#2]
When using binary_reader, I got the following error from TypeScript:
```
error: TS2729 [ERROR]: Property 'buffer' is used before its initialization.
    this.buffer.buffer,
         ~~~~~~
    at https://deno.land/x/binary_reader@v0.1.5/binary_reader.ts:3:10      

    'buffer' is declared here.
      constructor(private buffer: Uint8Array) {}
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
        at https://deno.land/x/binary_reader@v0.1.5/binary_reader.ts:9:15

TS2729 [ERROR]: Property 'buffer' is used before its initialization.
    this.buffer.byteOffset,
         ~~~~~~
    at https://deno.land/x/binary_reader@v0.1.5/binary_reader.ts:4:10

    'buffer' is declared here.
      constructor(private buffer: Uint8Array) {}
        at https://deno.land/x/binary_reader@v0.1.5/binary_reader.ts:9:15

TS2729 [ERROR]: Property 'buffer' is used before its initialization.
    this.buffer.byteLength,
         ~~~~~~
    at https://deno.land/x/binary_reader@v0.1.5/binary_reader.ts:5:10

    'buffer' is declared here.
      constructor(private buffer: Uint8Array) {}
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
        at https://deno.land/x/binary_reader@v0.1.5/binary_reader.ts:9:15

Found 3 errors.
```

The problem is that the code to create `dataBuffer`, is being run before the constructor, and therefore before `buffer` is initialised.

[Link to the code](https://github.com/jsimpson/binary_reader/blob/master/binary_reader.ts#L3-L5)

I have created a pull request with a fix: #1 

This is my first time making a pull request, so if there's anything in the process that I've done wrong, please let me know.

**Comment by jsimpson** [comment]
Thanks, @ThatBlockyPenguin, this is great! I've merged your PR. I appreciate the contribution!
